@echo off
echo Please wait for the oobesetup to load...
echo ...
ping localhost -n 2 >nul
echo ...
ping localhost -n 2 >nul
echo Done.
ping localhost -n 1 >nul
echo Input the drive letter of your Edo OS GUI installation followed with a colon.
set /p diskinstall=
cls
echo.
echo [==========================================]
ping localhost -n 1 >nul
echo [Error - Setup encountered an error.       ]
ping localhost -n 1 >nul
echo [==========================================]
ping localhost -n 1 >nul
echo [ Setup encountered an non-fatal error as  ]
ping localhost -n 1 >nul
echo [ described below.                         ]
ping localhost -n 1 >nul
echo [ GUI-OOBE could not initialize. Backup    ]
ping localhost -n 1 >nul
echo [ text-based theme applied. ERR=000000x19  ]
ping localhost -n 1 >nul
echo [     -=Press any key to start OOBE=-      ]
ping localhost -n 1 >nul
echo [__________________________________________]
ping localhost -n 1 >nul
pause >nul
ping localhost -n 2 >nul
cls
mode 100,33
echo +======+======================================================================================]
echo [=PROGRESS=]                                                                                  ]
echo [----------]                                                                                  ]
echo [INSTALL * ]                                                                                  ]
echo [          ]                                                                                  ]
echo [SETUP   * ]                                                                                  ]
echo [          ]                                                                                  ]
echo [CHECK   * ]                                                                                  ]
echo [          ]                                                                                  ]
echo [----------]                                Please wait...                                    ]
echo [          ]                               -==============-                                   ]
echo [USRNAME + ]                             OOBE-START loading...                                ]
echo [          ]                                                                                  ]
echo [PASSWRD + ]                                                                                  ]
echo [          ]                                                                                  ]
echo [----------]                                                                                  ]
echo [          ]                                                                                  ]
echo [CHECK   + ]                                                                                  ]
echo [          ]                                                                                  ]
echo [BSTDISK + ]                                                                                  ]
echo [          ]                                                                                  ]
echo [----------]                                                                                  ]
echo [          ]                                                                                  ]
echo [CHECK   + ]                                                                                  ]
echo [          ]                                                                                  ]
echo [APPS    + ]                                                                                  ]
echo [          ]                                                                                  ]
echo [CHECK   + ]                                                                                  ]
echo [          ]                                                                                  ]
echo [DESKTOP + ]                                                                                  ]
echo [          ]                                                                                  ]
echo +======+======================================================================================]
ping localhost -n 3 >nul

echo +======+======================================================================================]
echo [=PROGRESS=]                                                                                  ]
echo [----------]                                                                                  ]
echo [INSTALL * ]                                                                                  ]
echo [          ]                                                                                  ]
echo [SETUP   * ]                                                                                  ]
echo [          ]                                                                                  ]
echo [CHECK   * ]                                                                                  ]
echo [          ]                                                                                  ]
echo [----------]                                Please wait...                                    ]
echo [          ]                               -==============-                                   ]
echo [USRNAME + ]                             TEXT-INPUT Loading...                                ]
echo [          ]                                                                                  ]
echo [PASSWRD + ]                                                                                  ]
echo [          ]                                                                                  ]
echo [----------]                                                                                  ]
echo [          ]                                                                                  ]
echo [CHECK   + ]                                                                                  ]
echo [          ]                                                                                  ]
echo [BSTDISK + ]                                                                                  ]
echo [          ]                                                                                  ]
echo [----------]                                                                                  ]
echo [          ]                                                                                  ]
echo [CHECK   + ]                                                                                  ]
echo [          ]                                                                                  ]
echo [APPS    + ]                                                                                  ]
echo [          ]                                                                                  ]
echo [CHECK   + ]                                                                                  ]
echo [          ]                                                                                  ]
echo [DESKTOP + ]                                                                                  ]
echo [          ]                                                                                  ]
echo +======+======================================================================================]
ping localhost -n 3 >nul

echo +======+======================================================================================]
echo [=PROGRESS=]                                                                                  ]
echo [----------]                                                                                  ]
echo [INSTALL * ]                                                                                  ]
echo [          ]                                                                                  ]
echo [SETUP   * ]                                                                                  ]
echo [          ]                                                                                  ]
echo [CHECK   * ]                                                                                  ]
echo [          ]                                                                                  ]
echo [----------]                                Please wait...                                    ]
echo [          ]                               -==============-                                   ]
echo [USRNAME + ]                                  Loading...                                      ]
echo [          ]                                                                                  ]
echo [PASSWRD + ]                                                                                  ]
echo [          ]                                                                                  ]
echo [----------]                                                                                  ]
echo [          ]                                                                                  ]
echo [CHECK   + ]                                                                                  ]
echo [          ]                                                                                  ]
echo [BSTDISK + ]                                                                                  ]
echo [          ]                                                                                  ]
echo [----------]                                                                                  ]
echo [          ]                                                                                  ]
echo [CHECK   + ]                                                                                  ]
echo [          ]                                                                                  ]
echo [APPS    + ]                                                                                  ]
echo [          ]                                                                                  ]
echo [CHECK   + ]                                                                                  ]
echo [          ]                                                                                  ]
echo [DESKTOP + ]                                                                                  ]
echo [          ]                                                                                  ]
echo +======+======================================================================================]
ping localhost -n 3 >nul

echo +======+======================================================================================]
echo [=PROGRESS=]Create an account]                                                                ]
echo [----------]=================]                                                                ]
echo [INSTALL * ]                                                                                  ]
echo [          ]                                                                                  ]
echo [SETUP   * ]                                                                                  ]
echo [          ]                                                                                  ]
echo [CHECK   * ]                                                                                  ]
echo [          ]                                                                                  ]
echo [----------]                                Create an Account.                                ]
echo [          ]                                 Enter your Name.                                 ]
echo [USRNAME + ]                                                                                  ]
echo [          ]                                                                                  ]
echo [PASSWRD + ]                                                                                  ]
echo [          ]                                                                                  ]
echo [----------]                                                                                  ]
echo [          ]                                                                                  ]
echo [CHECK   + ]                                                                                  ]
echo [          ]                                                                                  ]
echo [BSTDISK + ]                                                                                  ]
echo [          ]                                                                                  ]
echo [----------]                                                                                  ]
echo [          ]                                                                                  ]
echo [CHECK   + ]                                                                                  ]
echo [          ]                                                                                  ]
echo [APPS    + ]                                                                                  ]
echo [          ]                                                                                  ]
echo [CHECK   + ]                                                                                  ]
echo [          ]                                                                                  ]
echo [DESKTOP + ]                                                                                  ]
echo [          ]                                                                                  ]
echo +======+======================================================================================]
batbox /g 44 11 /d ">"
set /p setupusrname=
echo %setupusrname% > users.txt

echo +======+======================================================================================]
echo [=PROGRESS=]Create an account]                                                                ]
echo [----------]=================]                                                                ]
echo [INSTALL * ]                                                                                  ]
echo [          ]                                                                                  ]
echo [SETUP   * ]                                                                                  ]
echo [          ]                                                                                  ]
echo [CHECK   * ]                                                                                  ]
echo [          ]                                                                                  ]
echo [----------]                                Create an Account.                                ]
echo [          ]                        Enter a Password. (Make it secure!)                       ]
echo [USRNAME * ]                                                                                  ]
echo [          ]                                                                                  ]
echo [PASSWRD + ]                                                                                  ]
echo [          ]                                                                                  ]
echo [----------]                                                                                  ]
echo [          ]                                                                                  ]
echo [CHECK   + ]                                                                                  ]
echo [          ]                                                                                  ]
echo [BSTDISK + ]                                                                                  ]
echo [          ]                                                                                  ]
echo [----------]                                                                                  ]
echo [          ]                                                                                  ]
echo [CHECK   + ]                                                                                  ]
echo [          ]                                                                                  ]
echo [APPS    + ]                                                                                  ]
echo [          ]                                                                                  ]
echo [CHECK   + ]                                                                                  ]
echo [          ]                                                                                  ]
echo [DESKTOP + ]                                                                                  ]
echo [          ]                                                                                  ]
echo +======+======================================================================================]
batbox /g 44 11 /d ">"
set /p setuppassword=
echo %setuppassword% > pass.txt

echo +======+======================================================================================]
echo [=PROGRESS=]                                                                                  ]
echo [----------]                                                                                  ]
echo [INSTALL * ]                                                                                  ]
echo [          ]                                                                                  ]
echo [SETUP   * ]                                                                                  ]
echo [          ]                                                                                  ]
echo [CHECK   * ]                               ___________________                                ]
echo [          ]                              [                   ]                               ]
echo [----------]                              [  Please wait...   ]                               ]
echo [          ]                              [ Checking files... ]                               ]
echo [USRNAME * ]                              [___________________]                               ]
echo [          ]                                                                                  ]
echo [PASSWRD * ]                                                                                  ]
echo [          ]                                                                                  ]
echo [----------]                                                                                  ]
echo [          ]                                                                                  ]
echo [CHECK   + ]                                                                                  ]
echo [          ]                                                                                  ]
echo [BSTDISK + ]                                                                                  ]
echo [          ]                                                                                  ]
echo [----------]                                                                                  ]
echo [          ]                                                                                  ]
echo [CHECK   + ]                                                                                  ]
echo [          ]                                                                                  ]
echo [APPS    + ]                                                                                  ]
echo [          ]                                                                                  ]
echo [CHECK   + ]                                                                                  ]
echo [          ]                                                                                  ]
echo [DESKTOP + ]                                                                                  ]
echo [          ]                                                                                  ]
echo +======+======================================================================================]
ping localhost -n 4 >nul

echo +======+======================================================================================]
echo [=PROGRESS=]                                                                                  ]
echo [----------]                                                                                  ]
echo [INSTALL * ]                                                                                  ]
echo [          ]                                                                                  ]
echo [SETUP   * ]                                                                                  ]
echo [          ]                     ___________________________________________                  ]
echo [CHECK   * ]                    [                                           ]                 ]
echo [          ]                    [        If you have a Boost Disk,          ]                 ]
echo [----------]                    [     insert it now. (If you installed      ]                 ]
echo [          ]                    [  this OS from GitHub, you can skip this)  ]                 ]
echo [USRNAME * ]                    [___________________________________________]                 ]
echo [          ]                                                                                  ]
echo [PASSWRD * ]               Type the Disk Drive Letter followed by a Colon to install.         ]
echo [          ]                               Type "none" to skip.                               ]
echo [----------]                                                                                  ]
echo [          ]                                                                                  ]
echo [CHECK   * ]                                                                                  ]
echo [          ]                                                                                  ]
echo [BSTDISK + ]                                                                                  ]
echo [          ]                                                                                  ]
echo [----------]                                                                                  ]
echo [          ]                                                                                  ]
echo [CHECK   + ]                                                                                  ]
echo [          ]                                                                                  ]
echo [APPS    + ]                                                                                  ]
echo [          ]                                                                                  ]
echo [CHECK   + ]                                                                                  ]
echo [          ]                                                                                  ]
echo [DESKTOP + ]                                                                                  ]
echo [          ]                                                                                  ]
echo +======+======================================================================================]
batbox /g 44 18 /d ">"
set /p bstdisk=
if %bstdisk%==none goto skipbst
%bstdisk%
call boostdiskinstall.bat


:skipbst

echo +======+======================================================================================]
echo [=PROGRESS=]                                                                                  ]
echo [----------]                                                                                  ]
echo [INSTALL * ]                                                                                  ]
echo [          ]                                                                                  ]
echo [SETUP   * ]                                                                                  ]
echo [          ]                                                                                  ]
echo [CHECK   * ]                                                                                  ]
echo [          ]                                                                                  ]
echo [----------]                                     Checking...                                  ]
echo [          ]                                  -==============-                                ]
echo [USRNAME * ]                                   Please wait...                                 ]
echo [          ]                                                                                  ]
echo [PASSWRD * ]                                                                                  ]
echo [          ]                                                                                  ]
echo [----------]                                                                                  ]
echo [          ]                                                                                  ]
echo [CHECK   * ]                                                                                  ]
echo [          ]                                                                                  ]
echo [BSTDISK * ]                                                                                  ]
echo [          ]                                                                                  ]
echo [----------]                                                                                  ]
echo [          ]                                                                                  ]
echo [CHECK   + ]                                                                                  ]
echo [          ]                                                                                  ]
echo [APPS    + ]                                                                                  ]
echo [          ]                                                                                  ]
echo [CHECK   + ]                                                                                  ]
echo [          ]                                                                                  ]
echo [DESKTOP + ]                                                                                  ]
echo [          ]                                                                                  ]
echo +======+======================================================================================]
ping localhost -n 3 >nul

echo +======+======================================================================================]
echo [=PROGRESS=]                                                                                  ]
echo [----------]                                                                                  ]
echo [INSTALL * ]                                                                                  ]
echo [          ]                                                                                  ]
echo [SETUP   * ]                                                                                  ]
echo [          ]                                                                                  ]
echo [CHECK   * ]                                                                                  ]
echo [          ]                                                                                  ]
echo [----------]                               Installing your Apps...                            ]
echo [          ]                                  -==============-                                ]
echo [USRNAME * ]                               (This may take a while)                            ]
echo [          ]                                                                                  ]
echo [PASSWRD * ]                                                                                  ]
echo [          ]                                                                                  ]
echo [----------]                                                                                  ]
echo [          ]                                                                                  ]
echo [CHECK   * ]                                                                                  ]
echo [          ]                                                                                  ]
echo [BSTDISK * ]                                                                                  ]
echo [          ]                                                                                  ]
echo [----------]                                                                                  ]
echo [          ]                                                                                  ]
echo [CHECK   * ]                                                                                  ]
echo [          ]                                                                                  ]
echo [APPS    + ]                                                                                  ]
echo [          ]                                                                                  ]
echo [CHECK   + ]                                                                                  ]
echo [          ]                                                                                  ]
echo [DESKTOP + ]                                                                                  ]
echo [          ]                                                                                  ]
echo +======+======================================================================================]
ping localhost -n 12 >nul
echo +======+======================================================================================]
echo [=PROGRESS=]                                                                                  ]
echo [----------]                                                                                  ]
echo [INSTALL * ]                                                                                  ]
echo [          ]                                                                                  ]
echo [SETUP   * ]                                                                                  ]
echo [          ]                                                                                  ]
echo [CHECK   * ]                                                                                  ]
echo [          ]                                                                                  ]
echo [----------]                                     Checking...                                  ]
echo [          ]                                  -==============-                                ]
echo [USRNAME * ]                                   Please wait...                                 ]
echo [          ]                                                                                  ]
echo [PASSWRD * ]                                                                                  ]
echo [          ]                                                                                  ]
echo [----------]                                                                                  ]
echo [          ]                                                                                  ]
echo [CHECK   * ]                                                                                  ]
echo [          ]                                                                                  ]
echo [BSTDISK * ]                                                                                  ]
echo [          ]                                                                                  ]
echo [----------]                                                                                  ]
echo [          ]                                                                                  ]
echo [CHECK   * ]                                                                                  ]
echo [          ]                                                                                  ]
echo [APPS    * ]                                                                                  ]
echo [          ]                                                                                  ]
echo [CHECK   + ]                                                                                  ]
echo [          ]                                                                                  ]
echo [DESKTOP + ]                                                                                  ]
echo [          ]                                                                                  ]
echo +======+======================================================================================]
ping localhost -n 5 >nul
echo +======+======================================================================================]
echo [=PROGRESS=]                                                                                  ]
echo [----------]                                                                                  ]
echo [INSTALL * ]                                                                                  ]
echo [          ]                                                                                  ]
echo [SETUP   * ]                                                                                  ]
echo [          ]                                                                                  ]
echo [CHECK   * ]                                                                                  ]
echo [          ]                                                                                  ]
echo [----------]                                 Preparing session...                             ]
echo [          ]                                  -==============-                                ]
echo [USRNAME * ]                               Preparing the desktop...                           ]
echo [          ]                                                                                  ]
echo [PASSWRD * ]                                                                                  ]
echo [          ]                                                                                  ]
echo [----------]                                                                                  ]
echo [          ]                                                                                  ]
echo [CHECK   * ]                                                                                  ]
echo [          ]                                                                                  ]
echo [BSTDISK * ]                                                                                  ]
echo [          ]                                                                                  ]
echo [----------]                           Waiting for the Logon Manager...                       ]
echo [          ]                                                                                  ]
echo [CHECK   * ]                                                                                  ]
echo [          ]                                                                                  ]
echo [APPS    * ]                                                                                  ]
echo [          ]                                                                                  ]
echo [CHECK   * ]                                                                                  ]
echo [          ]                                                                                  ]
echo [DESKTOP + ]                                                                                  ]
echo [          ]                                                                                  ]
echo +======+======================================================================================]
ping localhost -n 4 >nul

echo +======+======================================================================================]
echo [=PROGRESS=]                                                                                  ]
echo [----------]                                                                                  ]
echo [INSTALL * ]                                                                                  ]
echo [          ]                                                                                  ]
echo [SETUP   * ]                                                                                  ]
echo [          ]                                                                                  ]
echo [CHECK   * ]                                                                                  ]
echo [          ]                                                                                  ]
echo [----------]                                                                                  ]
echo [          ]                                                                                  ]
echo [USRNAME * ]                                   Please wait...                                 ]
echo [          ]                                                                                  ]
echo [PASSWRD * ]                                                                                  ]
echo [          ]                                                                                  ]
echo [----------]                                                                                  ]
echo [          ]                                                                                  ]
echo [CHECK   * ]                                                                                  ]
echo [          ]                                                                                  ]
echo [BSTDISK * ]                                                                                  ]
echo [          ]                                                                                  ]
echo [----------]                                                                                  ]
echo [          ]                                                                                  ]
echo [CHECK   * ]                                                                                  ]
echo [          ]                                                                                  ]
echo [APPS    * ]                                                                                  ]
echo [          ]                                                                                  ]
echo [CHECK   * ]                                                                                  ]
echo [          ]                                                                                  ]
echo [DESKTOP * ]                                                                                  ]
echo [          ]                                                                                  ]
echo +======+======================================================================================]
ping localhost -n 4 >nul
cls
%diskinstall%
call FCP.bat